server:
  port: 8101
spring:
  application:
    name: AC-OJ-BACKEND-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: www.ghost-ubuntu.org:8848
        group: AC-OJ
    gateway:
      routes:
        - id: AC-OJ-BACKEND-USER-SERVICE
          uri: lb://AC-OJ-BACKEND-USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: AC-OJ-BACKEND-QUESTION-SERVICE
          uri: lb://AC-OJ-BACKEND-QUESTION-SERVICE
          predicates:
            - Path=/api/question/**
        - id: AC-OJ-BACKEND-JUDGE-SERVICE
          uri: lb://AC-OJ-BACKEND-JUDGE-SERVICE
          predicates:
            - Path=/api/judge/**


knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2